#!/usr/bin/env python3
"""
docs-check.py - mechanical check of the generated documentation.

SYNOPSIS
    python scripts/docs-check.py <map> <docs-dir> [--fact PATTERN ...]
    python scripts/docs-check.py --file <path> [--fact PATTERN ...]

WHAT IT DOES
    Verifies the pages under <docs-dir> against the map and against the
    rules of a page (`.claude/agents/docs-writer.md`), and prints every
    failure with its file and line:
      - every entry of the map not in state `remove` has its page, and
        no page lies in <docs-dir> that the map does not name (the
        index `README.md` excepted);
      - every relative link to a `.md` file resolves;
      - no long dash (em or en) on any page;
      - every page opens with a front-matter;
      - no instance fact: the values of `CLAUDE.local.md` at the
        engine root (every word of four letters or more in a value,
        looked for outside URLs: a published address is public by
        nature, and which addresses a page may carry is the map's
        `must-not`), any e-mail address but a placeholder at
        `example.*`, any absolute path of a machine (a drive letter,
        a user's home directory), and every `--fact` pattern given.
    With `--file <path>` in place of a map and a directory, one file is
    scanned for instance facts only: the values of `CLAUDE.local.md`,
    an absolute path of a machine and the `--fact` patterns. No map,
    no links, no dash and no e-mail rule: this is the scan `/render`
    runs on a render it has just written (POS.0950), and a render may
    carry an address its recipe fixes (POS.0990).
    Exit code 0 when everything holds, 1 when anything fails.

    The check mends nothing: a page that fails is regenerated by the
    documentation command (`.claude/skills/document/SKILL.md`, step
    6), never edited by hand.

WHAT IT NEEDS
    Python 3.8 or newer. `docs_map.py` beside it. Nothing else.

NOTES
    The script carries no name, address or host of its own: the
    instance facts it looks for are read from `CLAUDE.local.md` at run
    time, which is why the file is read here and nowhere reaches a
    page. A match is reported with the line, so a false hit (a common
    word that happens to be a value) is seen and the rule, not the
    page, is adjusted.

EXAMPLES
    python scripts/docs-check.py projects/forge/docs-map.md docs
    python scripts/docs-check.py projects/<slug>/docs-map.md projects/<slug>/docs --fact acme
    python scripts/docs-check.py --file README.md
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import docs_map  # noqa: E402

GENERIC = [
    re.compile(r"[\w.+-]+@(?!example\.)[\w-]+\.[\w.-]+"),
    re.compile(r"\b[A-Za-z]:\\"),
    re.compile(r"/Users/|/home/"),
]
DASH_RE = re.compile("[—–]")
LINK_RE = re.compile(r"\]\(([^)#]+\.md)(#[^)]*)?\)")
URL_RE = re.compile(r"https?://\S+")


def local_facts(engine_root):
    f = engine_root / "CLAUDE.local.md"
    words = set()
    if not f.is_file():
        return words
    for line in f.read_text(encoding="utf-8", errors="replace").splitlines():
        if ":" not in line:
            continue
        _, _, value = line.partition(":")
        value = re.sub(r"\(.*?\)", " ", value)
        for w in re.findall(r"[A-Za-z][A-Za-z0-9_-]{3,}", value):
            words.add(w.lower())
    return words


def scan_file(path, engine_root, fact_patterns):
    """One file against the instance facts only: the values of
    CLAUDE.local.md, a machine's absolute path, the --fact patterns."""
    fact_res = [re.compile(re.escape(w), re.I) for w in sorted(local_facts(engine_root))]
    fact_res += [re.compile(p, re.I) for p in fact_patterns]
    machine = GENERIC[1:]
    failures = []
    text = path.read_text(encoding="utf-8", errors="replace")
    for i, line in enumerate(text.splitlines(), 1):
        no_urls = URL_RE.sub(" ", line)
        for rx in machine:
            if rx.search(line):
                failures.append(f"{path.as_posix()}:{i}: instance fact ({rx.pattern}): {line.strip()[:90]}")
                break
        else:
            for rx in fact_res:
                if rx.search(no_urls):
                    failures.append(f"{path.as_posix()}:{i}: instance fact ({rx.pattern}): {line.strip()[:90]}")
                    break
    if failures:
        print(f"1 file checked, {len(failures)} failures")
        for f in failures:
            print("  " + f)
        return 1
    print("1 file checked, no failure")
    return 0


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1].strip())
    ap.add_argument("map", nargs="?")
    ap.add_argument("docs", nargs="?")
    ap.add_argument("--fact", action="append", default=[], help="a pattern that must not appear")
    ap.add_argument("--file", help="scan this one file for instance facts only")
    a = ap.parse_args(argv)
    engine_root = Path(__file__).resolve().parent.parent
    if a.file:
        return scan_file(Path(a.file), engine_root, a.fact)
    if not (a.map and a.docs):
        ap.error("a map and a docs directory, or --file <path>")
    map_path = Path(a.map)
    front, entries = docs_map.parse(map_path.read_text(encoding="utf-8"))
    root = docs_map.target_root(map_path, front)
    docs_dir = Path(a.docs)

    failures = []
    expected = {e["path"] for e in entries if e["fields"].get("state", "").strip() != "remove"}
    present = {"docs/" + p.relative_to(docs_dir).as_posix()
               for p in docs_dir.rglob("*.md") if p.name != "README.md"}
    for m in sorted(expected - present):
        failures.append(f"missing page: {m}")
    for x in sorted(present - expected):
        failures.append(f"page not in the map: {x}")

    facts = local_facts(engine_root)
    fact_res = [re.compile(re.escape(w), re.I) for w in sorted(facts)]
    fact_res += [re.compile(p, re.I) for p in a.fact]

    for p in sorted(docs_dir.rglob("*.md")):
        text = p.read_text(encoding="utf-8", errors="replace")
        rel = p.relative_to(docs_dir).as_posix()
        if not text.startswith("---\n"):
            failures.append(f"{rel}: no front-matter")
        for i, line in enumerate(text.splitlines(), 1):
            if DASH_RE.search(line):
                failures.append(f"{rel}:{i}: long dash")
            # a published address is public by nature: the values of
            # CLAUDE.local.md are not looked for inside a URL, the
            # generic rules still apply to the whole line
            no_urls = URL_RE.sub(" ", line)
            for rx in GENERIC:
                if rx.search(line):
                    failures.append(f"{rel}:{i}: instance fact ({rx.pattern}): {line.strip()[:90]}")
                    break
            else:
                for rx in fact_res:
                    if rx.search(no_urls):
                        failures.append(f"{rel}:{i}: instance fact ({rx.pattern}): {line.strip()[:90]}")
                        break
        for m in LINK_RE.finditer(text):
            target = m.group(1)
            if "://" in target:
                continue
            if not (p.parent / target).resolve().exists():
                failures.append(f"{rel}: broken link {target}")

    pages = len(list(docs_dir.rglob("*.md")))
    if failures:
        print(f"{pages} files checked, {len(failures)} failures")
        for f in failures:
            print("  " + f)
        return 1
    print(f"{pages} files checked, no failure")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
